import pandas as pd
import matplotlib.pyplot as plt 

def visualize_scatter_plot(csv_file):
    #Read csv file
    df = pd.read_csv(csv_file)

    total = df.iloc[16].tolist()
    data_ = []
    for i in range(16):
        data_.append(df.iloc[i].tolist())

    fig = plt.figure()
    for i in range(16):
        plt.scatter(total[1::], data_[i][1::], label = data_[i][0])
   
    plt.xlabel("Total Revenue")
    plt.ylabel("Revenue")
    plt.title("Freight Revenue Generated by Each zone vs Total Revenue from March 2020 to January 2021", loc='center', wrap=True)
    plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    #plt.xlim([4000,18000])
    fig.savefig('scatter_plot.png', bbox_inches="tight")

if __name__=="__main__":
    data_file = 'RS_Session_253_AU1417.B.csv'
    visualize_scatter_plot(data_file)
